package de.bistrosoft.palaver.bestellverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import de.bistrosoft.palaver.artikelverwaltung.domain.Artikel;

/**
 * Bestellposition generated by hbm2java
 */
@Entity
@Table(name = "bestellposition", catalog = "palaver")
public class Bestellposition implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -3160765850839739452L;
	private Integer id;
	private Artikel artikel;
	private Bestellung bestellung;
	private int menge;

	public Bestellposition() {
	}

	public Bestellposition(Artikel artikel, Bestellung bestellung, int menge) {
		this.artikel = artikel;
		this.bestellung = bestellung;
		this.menge = menge;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "artikel_fk", nullable = false)
	public Artikel getArtikel() {
		return this.artikel;
	}

	public void setArtikel(Artikel artikel) {
		this.artikel = artikel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bestellung_fk", nullable = false)
	public Bestellung getBestellung() {
		return this.bestellung;
	}

	public void setBestellung(Bestellung bestellung) {
		this.bestellung = bestellung;
	}

	@Column(name = "menge", nullable = false)
	public int getMenge() {
		return this.menge;
	}

	public void setMenge(int menge) {
		this.menge = menge;
	}

}
