package de.bistrosoft.palaver.bestellverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import de.bistrosoft.palaver.lieferantenverwaltung.domain.Lieferant;

/**
 * Bestellung generated by hbm2java
 */
@Entity
@Table(name = "bestellung", catalog = "palaver")
public class Bestellung implements java.io.Serializable {

	
	private static final long serialVersionUID = 2910967887786078251L;
	private Long id;
	private Lieferant lieferant;
	private Date datum;
	private Set<Bestellposition> bestellpositions = new HashSet<Bestellposition>(
			0);

	public Bestellung() {
	}

	public Bestellung(Lieferant lieferant, Date datum) {
		this.lieferant = lieferant;
		this.datum = datum;
	}

	public Bestellung(Lieferant lieferant, Date datum,
			Set<Bestellposition> bestellpositions) {
		this.lieferant = lieferant;
		this.datum = datum;
		this.bestellpositions = bestellpositions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lieferant_fk", nullable = false)
	public Lieferant getLieferant() {
		return this.lieferant;
	}

	public void setLieferant(Lieferant lieferant) {
		this.lieferant = lieferant;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datum", nullable = false, length = 19)
	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bestellung")
	public Set<Bestellposition> getBestellpositions() {
		return this.bestellpositions;
	}

	public void setBestellpositions(Set<Bestellposition> bestellpositions) {
		this.bestellpositions = bestellpositions;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((bestellpositions == null) ? 0 : bestellpositions.hashCode());
		result = prime * result + ((datum == null) ? 0 : datum.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((lieferant == null) ? 0 : lieferant.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Bestellung other = (Bestellung) obj;
		if (bestellpositions == null) {
			if (other.bestellpositions != null)
				return false;
		} else if (!bestellpositions.equals(other.bestellpositions))
			return false;
		if (datum == null) {
			if (other.datum != null)
				return false;
		} else if (!datum.equals(other.datum))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (lieferant == null) {
			if (other.lieferant != null)
				return false;
		} else if (!lieferant.equals(other.lieferant))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Bestellung [id=" + id + ", lieferant=" + lieferant + ", datum="
				+ datum + ", bestellpositions=" + bestellpositions + "]";
	}

}
