package de.bistrosoft.palaver.bestellverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import de.bistrosoft.palaver.artikelverwaltung.domain.Artikel;

/**
 * Bestellposition generated by hbm2java
 */
@Entity
@Table(name = "bestellposition", catalog = "palaver")
public class Bestellposition implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -3160765850839739452L;
	private Long id;
	private Artikel artikel;
	private Bestellung bestellung;
	private int menge;

	public Bestellposition() {
	}

	public Bestellposition(Artikel artikel, Bestellung bestellung, int menge) {
		this.artikel = artikel;
		this.bestellung = bestellung;
		this.menge = menge;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "artikel_fk", nullable = false)
	public Artikel getArtikel() {
		return this.artikel;
	}

	public void setArtikel(Artikel artikel) {
		this.artikel = artikel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bestellung_fk", nullable = false)
	public Bestellung getBestellung() {
		return this.bestellung;
	}

	public void setBestellung(Bestellung bestellung) {
		this.bestellung = bestellung;
	}

	@Column(name = "menge", nullable = false)
	public int getMenge() {
		return this.menge;
	}

	public void setMenge(int menge) {
		this.menge = menge;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((artikel == null) ? 0 : artikel.hashCode());
		result = prime * result
				+ ((bestellung == null) ? 0 : bestellung.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + menge;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Bestellposition other = (Bestellposition) obj;
		if (artikel == null) {
			if (other.artikel != null)
				return false;
		} else if (!artikel.equals(other.artikel))
			return false;
		if (bestellung == null) {
			if (other.bestellung != null)
				return false;
		} else if (!bestellung.equals(other.bestellung))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (menge != other.menge)
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Bestellposition [id=" + id + ", artikel=" + artikel
				+ ", bestellung=" + bestellung + ", menge=" + menge + "]";
	}

}
