package de.hska.awp.palaver2.menueplanverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1


/**
 * Menueplan generated by hbm2java
 */

public class Menueplan implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 6664831562195094763L;
	private MenueplanId id;
	private Menue menue;

	public Menueplan() {
	}

	public Menueplan(MenueplanId id, Menue menue) {
		this.id = id;
		this.menue = menue;
	}

	public MenueplanId getId() {
		return this.id;
	}

	public void setId(MenueplanId id) {
		this.id = id;
	}

	public Menue getMenue() {
		return this.menue;
	}

	public void setMenue(Menue menue) {
		this.menue = menue;
	}

}
