package de.bistrosoft.palaver.mitarbeiterverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1
import java.util.HashSet;
import java.util.Set;

import de.bistrosoft.palaver.dienstplanverwaltung.domain.Schichtplan;
import de.bistrosoft.palaver.menueplanverwaltung.domain.Menue;
import de.hska.awp.palaver2.nachrichtenverwaltung.domain.Nachricht;
import de.bistrosoft.palaver.rezeptverwaltung.domain.Rezept;

/**
 * Mitarbeiter generated by hbm2java
 */
public class Mitarbeiter implements java.io.Serializable {

	private static final long serialVersionUID = 3570324130077272649L;
	private Long id;
	private String name;
	private String vorname;
	private String email;
	private String passwort;
	private String eintrittsdatum;
	private String austrittsdatum;
	private Set<Nachricht> nachrichten = new HashSet<Nachricht>(0);
	private Set<Rollen> rollens = new HashSet<Rollen>(0);



	public Mitarbeiter(){
		
	}
	
	public Mitarbeiter(String name, String vorname) {
		this.name = name;
		this.vorname = vorname;
	}

	public Mitarbeiter(Long id, String name, String vorname) {
		this.id = id;
		this.name = name;
		this.vorname = vorname;
	}

	public Mitarbeiter(String name, String vorname, String email,
			String passwort, String eintrittsdatum, String austrittsdatum,
			 Set<Nachricht> nachrichten,
			Set<Rollen> rollens) {
		this.name = name;
		this.vorname = vorname;
		this.email = email;
		this.passwort = passwort;
		this.eintrittsdatum = eintrittsdatum;
		this.austrittsdatum = austrittsdatum;
		
		this.nachrichten = nachrichten;
		this.rollens = rollens;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getVorname() {
		return this.vorname;
	}

	public void setVorname(String vorname) {
		this.vorname = vorname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPasswort() {
		return this.passwort;
	}

	public void setPasswort(String passwort) {
		this.passwort = passwort;
	}

	public String getEintrittsdatum() {
		return this.eintrittsdatum;
	}

	public void setEintrittsdatum(String eintrittsdatum) {
		this.eintrittsdatum = eintrittsdatum;
	}

	public String getAustrittsdatum() {
		return this.austrittsdatum;
	}

	public void setAustrittsdatum(String austrittsdatum) {
		this.austrittsdatum = austrittsdatum;
	}

	public Set<Nachricht> getNachrichten() {
		return this.nachrichten;
	}

	public void setNachrichten(Set<Nachricht> nachrichten) {
		this.nachrichten = nachrichten;
	}


	public Set<Rollen> getRollens() {
		return this.rollens;
	}

	public void setRollens(Set<Rollen> rollens) {
		this.rollens = rollens;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((austrittsdatum == null) ? 0 : austrittsdatum.hashCode());
		result = prime * result
				+ ((eintrittsdatum == null) ? 0 : eintrittsdatum.hashCode());
		result = prime * result + ((email == null) ? 0 : email.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		
		result = prime * result
				+ ((nachrichten == null) ? 0 : nachrichten.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result
				+ ((passwort == null) ? 0 : passwort.hashCode());
		
		result = prime * result + ((rollens == null) ? 0 : rollens.hashCode());
		
		result = prime * result + ((vorname == null) ? 0 : vorname.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Mitarbeiter other = (Mitarbeiter) obj;
		if (austrittsdatum == null) {
			if (other.austrittsdatum != null)
				return false;
		} else if (!austrittsdatum.equals(other.austrittsdatum))
			return false;
		if (eintrittsdatum == null) {
			if (other.eintrittsdatum != null)
				return false;
		} else if (!eintrittsdatum.equals(other.eintrittsdatum))
			return false;
		if (email == null) {
			if (other.email != null)
				return false;
		} else if (!email.equals(other.email))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (nachrichten == null) {
			if (other.nachrichten != null)
				return false;
		} else if (!nachrichten.equals(other.nachrichten))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (passwort == null) {
			if (other.passwort != null)
				return false;
		} else if (!passwort.equals(other.passwort))
			return false;
		if (rollens == null) {
			if (other.rollens != null)
				return false;
		} else if (!rollens.equals(other.rollens))
			return false;
		if (vorname == null) {
			if (other.vorname != null)
				return false;
		} else if (!vorname.equals(other.vorname))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return name;
	}


}
