package de.bistrosoft.palaver.mitarbeiterverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1
import java.util.HashSet;
import java.util.Set;

import de.hska.awp.palaver2.nachrichtenverwaltung.domain.Nachricht;

/**
 * Rollen generated by hbm2java
 */
public class Rollen implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7873088826047991256L;
	private Long id;
	private String name;
	private Set<Nachricht> nachrichten = new HashSet<Nachricht>(0);
	private Set<Mitarbeiter> mitarbeiters = new HashSet<Mitarbeiter>(0);

	public Rollen() {
	}

	public Rollen(String name) {
		this.name = name;
	}

	public Rollen(String name, Set<Nachricht> nachrichtens,
			Set<Mitarbeiter> mitarbeiters) {
		this.name = name;
		this.nachrichten = nachrichtens;
		this.mitarbeiters = mitarbeiters;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Nachricht> getNachrichten() {
		return this.nachrichten;
	}

	public void setNachrichten(Set<Nachricht> nachrichten) {
		this.nachrichten = nachrichten;
	}

	public Set<Mitarbeiter> getMitarbeiters() {
		return this.mitarbeiters;
	}

	public void setMitarbeiters(Set<Mitarbeiter> mitarbeiters) {
		this.mitarbeiters = mitarbeiters;
	}

}
