package de.bistrosoft.palaver.kuchenrezeptverwaltung.domain;

// Generated 25.04.2013 13:27:05 by Hibernate Tools 4.0.0

/**
 * RezeptHasArtikelId generated by hbm2java
 */
public class KuchenrezeptHasArtikelId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6342617785477300931L;
	/**
	 * 
	 */
	private int kuchenrezeptFk;
	private int artikelFk;

	public KuchenrezeptHasArtikelId() {
	}

	public KuchenrezeptHasArtikelId(int kuchenrezeptFk, int artikelFk) {
		this.kuchenrezeptFk = kuchenrezeptFk;
		this.artikelFk = artikelFk;
	}

	public int getKuchenrezeptFk() {
		return this.kuchenrezeptFk;
	}

	public void setKuchenrezeptFk(int kuchenrezeptFk) {
		this.kuchenrezeptFk = kuchenrezeptFk;
	}

	public int getArtikelFk() {
		return this.artikelFk;
	}

	public void setArtikelFk(int artikelFk) {
		this.artikelFk = artikelFk;
	}

	

	@Override
	public String toString() {
		return "KuchenrezeptHasArtikelId [kuchenrezeptFk=" + kuchenrezeptFk + ", artikelFk="
				+ artikelFk + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + artikelFk;
		result = prime * result + kuchenrezeptFk;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		KuchenrezeptHasArtikelId other = (KuchenrezeptHasArtikelId) obj;
		if (artikelFk != other.artikelFk)
			return false;
		if (kuchenrezeptFk != other.kuchenrezeptFk)
			return false;
		return true;
	}

}
