package de.hska.awp.palaver2.rezeptverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Rezepteigenschaften generated by hbm2java
 */

public class Rezepteigenschaften implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 3565419545618129944L;
	private Integer id;
	private String name;
	private Set<Rezept> rezepts = new HashSet<Rezept>(0);

	public Rezepteigenschaften() {
	}

	public Rezepteigenschaften(String name) {
		this.name = name;
	}

	public Rezepteigenschaften(String name, Set<Rezept> rezepts) {
		this.name = name;
		this.rezepts = rezepts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Rezept> getRezepts() {
		return this.rezepts;
	}

	public void setRezepts(Set<Rezept> rezepts) {
		this.rezepts = rezepts;
	}

}
