package de.hska.awp.palaver2.rezeptverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Rezepteigenschaften generated by hbm2java
 */
@Entity
@Table(name = "rezepteigenschaften", catalog = "palaver")
public class Rezepteigenschaften implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 3565419545618129944L;
	private Integer id;
	private String name;
	private Set<Rezept> rezepts = new HashSet<Rezept>(0);

	public Rezepteigenschaften() {
	}

	public Rezepteigenschaften(String name) {
		this.name = name;
	}

	public Rezepteigenschaften(String name, Set<Rezept> rezepts) {
		this.name = name;
		this.rezepts = rezepts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "rezept_has_rezepteigenschaften", catalog = "palaver", joinColumns = { @JoinColumn(name = "rezepteigenschaften_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "rezept_id", nullable = false, updatable = false) })
	public Set<Rezept> getRezepts() {
		return this.rezepts;
	}

	public void setRezepts(Set<Rezept> rezepts) {
		this.rezepts = rezepts;
	}

}
