package de.hska.awp.palaver2.rezeptverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RezeptHasArtikelId generated by hbm2java
 */
@Embeddable
public class RezeptHasArtikelId implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -1386638252211019358L;
	private int rezeptId;
	private int artikelId;

	public RezeptHasArtikelId() {
	}

	public RezeptHasArtikelId(int rezeptId, int artikelId) {
		this.rezeptId = rezeptId;
		this.artikelId = artikelId;
	}

	@Column(name = "rezept_id", nullable = false)
	public int getRezeptId() {
		return this.rezeptId;
	}

	public void setRezeptId(int rezeptId) {
		this.rezeptId = rezeptId;
	}

	@Column(name = "artikel_id", nullable = false)
	public int getArtikelId() {
		return this.artikelId;
	}

	public void setArtikelId(int artikelId) {
		this.artikelId = artikelId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RezeptHasArtikelId))
			return false;
		RezeptHasArtikelId castOther = (RezeptHasArtikelId) other;

		return (this.getRezeptId() == castOther.getRezeptId())
				&& (this.getArtikelId() == castOther.getArtikelId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRezeptId();
		result = 37 * result + this.getArtikelId();
		return result;
	}

}
