package de.hska.awp.palaver2.rezeptverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Zutatenkategorie generated by hbm2java
 */
@Entity
@Table(name = "zutatenkategorie", catalog = "palaver", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Zutatenkategorie implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -4066524484940093963L;
	private Integer id;
	private String name;
	private Set<RezeptHasArtikel> rezeptHasArtikels = new HashSet<RezeptHasArtikel>(
			0);

	public Zutatenkategorie() {
	}

	public Zutatenkategorie(String name) {
		this.name = name;
	}

	public Zutatenkategorie(String name, Set<RezeptHasArtikel> rezeptHasArtikels) {
		this.name = name;
		this.rezeptHasArtikels = rezeptHasArtikels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zutatenkategorie")
	public Set<RezeptHasArtikel> getRezeptHasArtikels() {
		return this.rezeptHasArtikels;
	}

	public void setRezeptHasArtikels(Set<RezeptHasArtikel> rezeptHasArtikels) {
		this.rezeptHasArtikels = rezeptHasArtikels;
	}

}
