package de.hska.awp.palaver2.mitarbeiterverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Rollen generated by hbm2java
 */

public class Rollen implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -3366000000412110979L;
	private Long id;
	private String name;
	private Set<Mitarbeiter> mitarbeiters = new HashSet<Mitarbeiter>(0);

	public Rollen() {
	}

	public Rollen(Long id,String name) {
		this.id = id;
		this.name = name;
	}

	public Rollen(String name, Set<Mitarbeiter> mitarbeiters) {
		this.name = name;
		this.mitarbeiters = mitarbeiters;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Mitarbeiter> getMitarbeiters() {
		return this.mitarbeiters;
	}

	public void setMitarbeiters(Set<Mitarbeiter> mitarbeiters) {
		this.mitarbeiters = mitarbeiters;
	}

}
