package de.hska.awp.palaver2.nachrichtenverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import de.hska.awp.palaver2.mitarbeiterverwaltung.domain.Mitarbeiter;

/**
 * Nachrichten generated by hbm2java
 */
@Entity
@Table(name = "nachrichten", catalog = "palaver")
public class Nachricht implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1291141882464373163L;
	private Long id;
	private Mitarbeiter mitarbeiterBySenderFk;
	private Mitarbeiter mitarbeiterByEmpfaengerFk;
	private String nachricht;

	public Nachricht() {
	}

	public Nachricht(Mitarbeiter mitarbeiterBySenderFk,
			Mitarbeiter mitarbeiterByEmpfaengerFk) {
		this.mitarbeiterBySenderFk = mitarbeiterBySenderFk;
		this.mitarbeiterByEmpfaengerFk = mitarbeiterByEmpfaengerFk;
	}

	public Nachricht(Mitarbeiter mitarbeiterBySenderFk,
			Mitarbeiter mitarbeiterByEmpfaengerFk, String nachricht) {
		this.mitarbeiterBySenderFk = mitarbeiterBySenderFk;
		this.mitarbeiterByEmpfaengerFk = mitarbeiterByEmpfaengerFk;
		this.nachricht = nachricht;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sender_fk", nullable = false)
	public Mitarbeiter getMitarbeiterBySenderFk() {
		return this.mitarbeiterBySenderFk;
	}

	public void setMitarbeiterBySenderFk(Mitarbeiter mitarbeiterBySenderFk) {
		this.mitarbeiterBySenderFk = mitarbeiterBySenderFk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "empfaenger_fk", nullable = false)
	public Mitarbeiter getMitarbeiterByEmpfaengerFk() {
		return this.mitarbeiterByEmpfaengerFk;
	}

	public void setMitarbeiterByEmpfaengerFk(
			Mitarbeiter mitarbeiterByEmpfaengerFk) {
		this.mitarbeiterByEmpfaengerFk = mitarbeiterByEmpfaengerFk;
	}

	@Column(name = "nachricht", length = 300)
	public String getNachricht() {
		return this.nachricht;
	}

	public void setNachricht(String nachricht) {
		this.nachricht = nachricht;
	}

}
