package de.bistrosoft.palaver.menueplanverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Menueplan generated by hbm2java
 */
@Entity
@Table(name = "menueplan", catalog = "palaver")
public class Menueplan implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 6664831562195094763L;
	private MenueplanId id;
	private Menue menue;

	public Menueplan() {
	}

	public Menueplan(MenueplanId id, Menue menue) {
		this.id = id;
		this.menue = menue;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "datum", column = @Column(name = "datum", nullable = false, length = 10)),
			@AttributeOverride(name = "position", column = @Column(name = "position", nullable = false)) })
	public MenueplanId getId() {
		return this.id;
	}

	public void setId(MenueplanId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menue", nullable = false)
	public Menue getMenue() {
		return this.menue;
	}

	public void setMenue(Menue menue) {
		this.menue = menue;
	}

}
