package de.hska.awp.palaver2.nachrichtenverwaltung.domain;

// Generated 21.04.2013 16:08:42 by PhilippT 



import de.hska.awp.palaver2.mitarbeiterverwaltung.domain.Mitarbeiter;
import de.hska.awp.palaver2.mitarbeiterverwaltung.domain.Rollen;

/**
 * Nachricht generated by PhilippT
 */

public class Nachricht implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1291141882464373163L;
	
	private Long id;
	private Mitarbeiter mitarbeiterBySenderFk;
	private Rollen empfaengerRolle;
	private String nachricht;

	public Nachricht() {
	}

	public Nachricht(Mitarbeiter mitarbeiterBySenderFk,
			Rollen empfaengerRolle) {
		this.mitarbeiterBySenderFk = mitarbeiterBySenderFk;
		this.empfaengerRolle = empfaengerRolle;
	}

	public Nachricht(Long id, String nachricht, Mitarbeiter mitarbeiterBySenderFk,
			Rollen empfaengerRolle) {
		this.id = id;
		this.nachricht = nachricht;
		this.mitarbeiterBySenderFk = mitarbeiterBySenderFk;
		this.empfaengerRolle = empfaengerRolle;

	}

	public Nachricht(Long id, String nachricht, Mitarbeiter mitarbeiterBySenderFk) {
		this.id = id;
		this.nachricht = nachricht;
		this.mitarbeiterBySenderFk = mitarbeiterBySenderFk;
	
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Mitarbeiter getMitarbeiterBySenderFk() {
		return this.mitarbeiterBySenderFk;
	}

	public void setMitarbeiterBySenderFk(Mitarbeiter mitarbeiterBySenderFk) {
		this.mitarbeiterBySenderFk = mitarbeiterBySenderFk;
	}

	public Rollen getEmpfaengerRolle() {
		return this.empfaengerRolle;
	}

	public void setEmpfaengerRolle(
			Rollen empfaengerRolle) {
		this.empfaengerRolle = empfaengerRolle;
	}

	public String getNachricht() {
		return this.nachricht;
	}

	public void setNachricht(String nachricht) {
		this.nachricht = nachricht;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Nachricht [id=" + id + ", nachricht=" + nachricht + "]";
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result
				+ ((nachricht == null) ? 0 : nachricht.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Nachricht other = (Nachricht) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (nachricht == null) {
			if (other.nachricht != null)
				return false;
		} else if (!nachricht.equals(other.nachricht))
			return false;
		return true;
	}

}
