package de.hska.awp.palaver2.dienstplanverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import de.hska.awp.palaver2.mitarbeiterverwaltung.domain.Mitarbeiter;

/**
 * Schichtplan generated by hbm2java
 */

public class Schichtplan implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -6839620055148237060L;
	private Integer id;
	private Mitarbeiter mitarbeiter;
	private Date datum;
	private Date arbeitsbeginn;
	private Date erbeitsende;

	public Schichtplan() {
	}

	public Schichtplan(Mitarbeiter mitarbeiter, Date datum, Date arbeitsbeginn,
			Date erbeitsende) {
		this.mitarbeiter = mitarbeiter;
		this.datum = datum;
		this.arbeitsbeginn = arbeitsbeginn;
		this.erbeitsende = erbeitsende;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Mitarbeiter getMitarbeiter() {
		return this.mitarbeiter;
	}

	public void setMitarbeiter(Mitarbeiter mitarbeiter) {
		this.mitarbeiter = mitarbeiter;
	}

	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	public Date getArbeitsbeginn() {
		return this.arbeitsbeginn;
	}

	public void setArbeitsbeginn(Date arbeitsbeginn) {
		this.arbeitsbeginn = arbeitsbeginn;
	}

	public Date getErbeitsende() {
		return this.erbeitsende;
	}

	public void setErbeitsende(Date erbeitsende) {
		this.erbeitsende = erbeitsende;
	}

}
