package de.hska.awp.palaver2.dienstplanverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import de.hska.awp.palaver2.mitarbeiterverwaltung.domain.Mitarbeiter;

/**
 * Schichtplan generated by hbm2java
 */
@Entity
@Table(name = "schichtplan", catalog = "palaver")
public class Schichtplan implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -6839620055148237060L;
	private Integer id;
	private Mitarbeiter mitarbeiter;
	private Date datum;
	private Date arbeitsbeginn;
	private Date erbeitsende;

	public Schichtplan() {
	}

	public Schichtplan(Mitarbeiter mitarbeiter, Date datum, Date arbeitsbeginn,
			Date erbeitsende) {
		this.mitarbeiter = mitarbeiter;
		this.datum = datum;
		this.arbeitsbeginn = arbeitsbeginn;
		this.erbeitsende = erbeitsende;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mitarbeiter", nullable = false)
	public Mitarbeiter getMitarbeiter() {
		return this.mitarbeiter;
	}

	public void setMitarbeiter(Mitarbeiter mitarbeiter) {
		this.mitarbeiter = mitarbeiter;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datum", nullable = false, length = 10)
	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "arbeitsbeginn", nullable = false, length = 8)
	public Date getArbeitsbeginn() {
		return this.arbeitsbeginn;
	}

	public void setArbeitsbeginn(Date arbeitsbeginn) {
		this.arbeitsbeginn = arbeitsbeginn;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "erbeitsende", nullable = false, length = 8)
	public Date getErbeitsende() {
		return this.erbeitsende;
	}

	public void setErbeitsende(Date erbeitsende) {
		this.erbeitsende = erbeitsende;
	}

}
