package de.hska.awp.palaver2.lieferantenverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Ansprechpartner generated by hbm2java
 */
@Entity
@Table(name = "ansprechpartner", catalog = "palaver")
@NamedQueries({
	@NamedQuery(name = Ansprechpartner.FIND_ANSPRECHPARTNER_BY_NAME,
				query = "SELECT k FROM Ansprechpartner k WHERE k.name = :" + Ansprechpartner.PARAM_NAME),
	@NamedQuery(name = Ansprechpartner.FIND_ANSPRECHPARTNER_ORDER_BY_ID,
				query = "Select k FROM Ansprechpartner k order by k.id")
	}
)
public class Ansprechpartner implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 8664124200867096510L;
	
	private static final String PREFIX = "Ansprechpartner.";
	
	public static final String FIND_ANSPRECHPARTNER_BY_NAME = PREFIX + "findAnsprechpartnerByName";
	public static final String FIND_ANSPRECHPARTNER_ORDER_BY_ID = PREFIX + "findAnsprechpartnerOrderById";
	public static final String PARAM_NAME = "name";
	public static final String PARAM_ID = "id"; 
	

	private Long id;
	
	
	private Lieferant lieferant;
	
	
	private String name;
	
	
	private String telefon;
	
	
	private String fax;

	public Ansprechpartner() {
	}

	public Ansprechpartner(Lieferant lieferant, String name) {
		this.lieferant = lieferant;
		this.name = name;
	}

	public Ansprechpartner(Lieferant lieferant, String name, String telefon,
			String fax) {
		this.lieferant = lieferant;
		this.name = name;
		this.telefon = telefon;
		this.fax = fax;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lieferant_fk", nullable = false)
	public Lieferant getLieferant() {
		return this.lieferant;
	}

	public void setLieferant(Lieferant lieferant) {
		this.lieferant = lieferant;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "telefon", length = 45)
	public String getTelefon() {
		return this.telefon;
	}

	public void setTelefon(String telefon) {
		this.telefon = telefon;
	}

	@Column(name = "fax", length = 45)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Ansprechpartner [id=" + id + ", lieferant=" + lieferant
				+ ", name=" + name + ", telefon=" + telefon + ", fax=" + fax
				+ "]";
	}

	

}
