package de.hska.awp.palaver2.rezeptverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import de.hska.awp.palaver2.artikelverwaltung.domain.Artikel;
import de.hska.awp.palaver2.artikelverwaltung.domain.Mengeneinheit;

/**
 * RezeptHasArtikel generated by hbm2java
 */

public class RezeptHasArtikel implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -4850668343074296124L;
	private RezeptHasArtikelId id;
	private Artikel artikel;
	private Mengeneinheit mengeneinheit;
	private Zutatenkategorie zutatenkategorie;
	private Rezept rezept;
	private BigDecimal menge;

	public RezeptHasArtikel() {
	}

	public RezeptHasArtikel(RezeptHasArtikelId id, Artikel artikel,
			Mengeneinheit mengeneinheit, Zutatenkategorie zutatenkategorie,
			Rezept rezept, BigDecimal menge) {
		this.id = id;
		this.artikel = artikel;
		this.mengeneinheit = mengeneinheit;
		this.zutatenkategorie = zutatenkategorie;
		this.rezept = rezept;
		this.menge = menge;
	}

	public RezeptHasArtikelId getId() {
		return this.id;
	}

	public void setId(RezeptHasArtikelId id) {
		this.id = id;
	}

	public Artikel getArtikel() {
		return this.artikel;
	}

	public void setArtikel(Artikel artikel) {
		this.artikel = artikel;
	}

	public Mengeneinheit getMengeneinheit() {
		return this.mengeneinheit;
	}

	public void setMengeneinheit(Mengeneinheit mengeneinheit) {
		this.mengeneinheit = mengeneinheit;
	}

	public Zutatenkategorie getZutatenkategorie() {
		return this.zutatenkategorie;
	}

	public void setZutatenkategorie(Zutatenkategorie zutatenkategorie) {
		this.zutatenkategorie = zutatenkategorie;
	}

	public Rezept getRezept() {
		return this.rezept;
	}

	public void setRezept(Rezept rezept) {
		this.rezept = rezept;
	}

	public BigDecimal getMenge() {
		return this.menge;
	}

	public void setMenge(BigDecimal menge) {
		this.menge = menge;
	}

}
