package de.hska.awp.palaver2.rezeptverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import de.hska.awp.palaver2.menueplanverwaltung.domain.Menue;

/**
 * Rezept generated by hbm2java
 */

public class Rezept implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -4913397461270724132L;
	private Integer id;
	private Rezeptart rezeptart;
	private String name;
	private Set<Rezepteigenschaften> rezepteigenschaftens = new HashSet<Rezepteigenschaften>(
			0);
	private Set<Menue> menues = new HashSet<Menue>(0);
	private Set<RezeptHasArtikel> rezeptHasArtikels = new HashSet<RezeptHasArtikel>(
			0);

	public Rezept() {
	}

	public Rezept(Rezeptart rezeptart, String name) {
		this.rezeptart = rezeptart;
		this.name = name;
	}

	public Rezept(Rezeptart rezeptart, String name,
			Set<Rezepteigenschaften> rezepteigenschaftens, Set<Menue> menues,
			Set<RezeptHasArtikel> rezeptHasArtikels) {
		this.rezeptart = rezeptart;
		this.name = name;
		this.rezepteigenschaftens = rezepteigenschaftens;
		this.menues = menues;
		this.rezeptHasArtikels = rezeptHasArtikels;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Rezeptart getRezeptart() {
		return this.rezeptart;
	}

	public void setRezeptart(Rezeptart rezeptart) {
		this.rezeptart = rezeptart;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public Set<Rezepteigenschaften> getRezepteigenschaftens() {
		return this.rezepteigenschaftens;
	}

	public void setRezepteigenschaftens(
			Set<Rezepteigenschaften> rezepteigenschaftens) {
		this.rezepteigenschaftens = rezepteigenschaftens;
	}

	public Set<Menue> getMenues() {
		return this.menues;
	}

	public void setMenues(Set<Menue> menues) {
		this.menues = menues;
	}

	public Set<RezeptHasArtikel> getRezeptHasArtikels() {
		return this.rezeptHasArtikels;
	}

	public void setRezeptHasArtikels(Set<RezeptHasArtikel> rezeptHasArtikels) {
		this.rezeptHasArtikels = rezeptHasArtikels;
	}

}
