package de.hska.awp.palaver2.rezeptverwaltung.domain;

// Generated 21.04.2013 16:08:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Zutatenkategorie generated by hbm2java
 */

public class Zutatenkategorie implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -4066524484940093963L;
	private Integer id;
	private String name;
	private Set<RezeptHasArtikel> rezeptHasArtikels = new HashSet<RezeptHasArtikel>(
			0);

	public Zutatenkategorie() {
	}

	public Zutatenkategorie(String name) {
		this.name = name;
	}

	public Zutatenkategorie(String name, Set<RezeptHasArtikel> rezeptHasArtikels) {
		this.name = name;
		this.rezeptHasArtikels = rezeptHasArtikels;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<RezeptHasArtikel> getRezeptHasArtikels() {
		return this.rezeptHasArtikels;
	}

	public void setRezeptHasArtikels(Set<RezeptHasArtikel> rezeptHasArtikels) {
		this.rezeptHasArtikels = rezeptHasArtikels;
	}

}
