package de.bistrosoft.palaver.rezeptverwaltung.domain;

// Generated 24.04.2013 16:47:07 by Hibernate Tools 4.0.0
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Rezeptart generated by hbm2java
 */
@Entity
@Table(name = "rezeptart", catalog = "palaver", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Rezeptart implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3791004464836691661L;
	private Long id;
	private String name;
	private Set<Rezept> rezepts = new HashSet<Rezept>(0);

	public Rezeptart() {
	}

	public Rezeptart(Long id, String name) {
		this.id =id;
		this.name = name;
	}

	public Rezeptart(Long id, String name, Set<Rezept> rezepts) {
		this.id = id;
		this.name = name;
		this.rezepts = rezepts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rezeptart")
	public Set<Rezept> getRezepts() {
		return this.rezepts;
	}

	public void setRezepts(Set<Rezept> rezepts) {
		this.rezepts = rezepts;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((rezepts == null) ? 0 : rezepts.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Rezeptart other = (Rezeptart) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (rezepts == null) {
			if (other.rezepts != null)
				return false;
		} else if (!rezepts.equals(other.rezepts))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Rezeptart [id=" + id + ", name=" + name + ", rezepts="
				+ rezepts + "]";
	}

}
