package de.bistrosoft.palaver.rezeptverwaltung.domain;

// Generated 24.04.2013 16:47:07 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RezeptHasFussnote generated by hbm2java
 */
@Entity
@Table(name = "rezept_has_fussnote", catalog = "palaver")
public class RezeptHasFussnote implements java.io.Serializable {

	private RezeptHasFussnoteId id;
	private Fussnote fussnote;
	private Rezept rezept;

	public RezeptHasFussnote() {
	}

	public RezeptHasFussnote(RezeptHasFussnoteId id, Fussnote fussnote,
			Rezept rezept) {
		this.id = id;
		this.fussnote = fussnote;
		this.rezept = rezept;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "rezeptFk", column = @Column(name = "rezept_fk", nullable = false)),
			@AttributeOverride(name = "fussnoteFk", column = @Column(name = "fussnote_fk", nullable = false)) })
	public RezeptHasFussnoteId getId() {
		return this.id;
	}

	public void setId(RezeptHasFussnoteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fussnote_fk", nullable = false, insertable = false, updatable = false)
	public Fussnote getFussnote() {
		return this.fussnote;
	}

	public void setFussnote(Fussnote fussnote) {
		this.fussnote = fussnote;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rezept_fk", nullable = false, insertable = false, updatable = false)
	public Rezept getRezept() {
		return this.rezept;
	}

	public void setRezept(Rezept rezept) {
		this.rezept = rezept;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((fussnote == null) ? 0 : fussnote.hashCode());
		result = prime * result + ((rezept == null) ? 0 : rezept.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		RezeptHasFussnote other = (RezeptHasFussnote) obj;
		if (fussnote == null) {
			if (other.fussnote != null)
				return false;
		} else if (!fussnote.equals(other.fussnote))
			return false;
		if (rezept == null) {
			if (other.rezept != null)
				return false;
		} else if (!rezept.equals(other.rezept))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "RezeptHasFussnote [fussnote=" + fussnote + ", rezept=" + rezept
				+ "]";
	}

}
