package de.bistrosoft.palaver.rezeptverwaltung.domain;

// Generated 24.04.2013 16:47:07 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Zubereitung generated by hbm2java
 */
@Entity
@Table(name = "zubereitung", catalog = "palaver", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Zubereitung implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -962227872830047781L;
	private Long id;
	private String name;
	private Set<RezeptHasZubereitung> rezeptHasZubereitungs = new HashSet<RezeptHasZubereitung>(
			0);

	public Zubereitung() {
	}

	public Zubereitung(Long id, String name) {
		this.id = id;
		this.name = name;
	}

	public Zubereitung(Long id, String name,
			Set<RezeptHasZubereitung> rezeptHasZubereitungs) {
		this.id = id;
		this.name = name;
		this.rezeptHasZubereitungs = rezeptHasZubereitungs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zubereitung")
	public Set<RezeptHasZubereitung> getRezeptHasZubereitungs() {
		return this.rezeptHasZubereitungs;
	}

	public void setRezeptHasZubereitungs(
			Set<RezeptHasZubereitung> rezeptHasZubereitungs) {
		this.rezeptHasZubereitungs = rezeptHasZubereitungs;
	}

	

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime
				* result
				+ ((rezeptHasZubereitungs == null) ? 0 : rezeptHasZubereitungs
						.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Zubereitung other = (Zubereitung) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (rezeptHasZubereitungs == null) {
			if (other.rezeptHasZubereitungs != null)
				return false;
		} else if (!rezeptHasZubereitungs.equals(other.rezeptHasZubereitungs))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Zubereitung [id=" + id + ", name=" + name
				+ ", rezeptHasZubereitungs=" + rezeptHasZubereitungs + "]";
	}

}
